apiVersion: v1
kind: Pod
metadata:
  name: k8s-sample-app2
spec:
  containers:
  - name: k8s-sample-app2
    image: alpine:3.5
    command: ["/bin/ash"]
    args: ["-c", "apk update && apk upgrade && apk add --upgrade curl && curl http://k8s-sample-app:8080/bar"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi

