apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongo-app
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      namespace: mongo-app
      name: mongo-express
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-user
                  key: mongo-db-root-user-name
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-user
                  key: mongo-db-root-user-name
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: data-base-url
                  name: mongo-app-configs

---

apiVersion: v1
kind: Service
metadata:
  namespace: mongo-app
  name: mongo-express-external-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30111
      protocol: TCP